### ISSUE TITLE
JSONDecodeError: Expecting value: line 3 column 1 (char 2)

### ISSUE THREAD

**Issue by imahamat** [btcpayserver/btcpay-python#11]
I am getting error **JSONDecodeError: Expecting value: line 3 column 1 (char 2)**  when trying to create or get an invoices.
The URL I use for the API calls works fine in the browser when creating a new BTCPay client, but gives this error when creating or getting an invoices within the BTCPay client.

<img width="621" alt="Create invoice" src="https://user-images.githubusercontent.com/35899660/71879749-1db75700-312f-11ea-8def-48be0f279095.png">

<img width="620" alt="Get a list of invoices matching certain parameters" src="https://user-images.githubusercontent.com/35899660/71879761-26a82880-312f-11ea-98d9-7bd30c92f1c5.png">

**Comment by JeffVandrewJr** [comment]
I've never seen this issue come up with that dependency, but it does appear you're using a very outdated version of Python. As a start, I'd suggest trying with a current Python version.

**Comment by thehapax** [comment]
> I've never seen this issue come up with that dependency, but it does appear you're using a very outdated version of Python. As a start, I'd suggest trying with a current Python version.

What version do you recommend for python? I've tried python3.6 and 3.7 when attempting to connect as client and I get this error: 

```raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://*******//tokens
```
when trying python3.5, I get this error: 

```
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:719)
```

**Comment by imahamat** [comment]
> I've never seen this issue come up with that dependency, but it does appear you're using a very outdated version of Python. As a start, I'd suggest trying with a current Python version.


I tried to use Jupyter Notebook in    [Colaboratory](<https://colab.research.google.com/notebooks/welcome.ipynb>) with Python 3.6.9 and  in [Anaconda](<https://www.anaconda.com/>) with Python 3.7.4. So What kind of jupyter environnement and python version  do you recommend ?

<img width="780" alt="Capture d’écran 2020-01-08 à 09 36 03" src="https://user-images.githubusercontent.com/35899660/72074692-aaf6d900-32f2-11ea-8e71-82b7ab858668.png">
<img width="572" alt="Capture d’écran 2020-01-08 à 09 35 43" src="https://user-images.githubusercontent.com/35899660/72074694-aaf6d900-32f2-11ea-9b95-58c44fad62e5.png">

The latest version of [Python is 3.8.1](<https://www.python.org/downloads/>)

**Comment by JeffVandrewJr** [comment]
@imahamat I unfortunately don't know anything about Jupyter, but I believe it's a bit of a walled garden.

I would suggest running in a real (non-Jupyter) environment.

**Comment by JeffVandrewJr** [comment]
@thehapax That has nothing to do with your Python version. It can't connect to your BTCPay, probably because you're either not running it on a domain or you don't have an SSL certificate for the domain.

With your issue, the Python library is working correctly; you have an issue on the BTCPay side (probably one of the issues I mention above).

**Comment by thehapax** [comment]
> @thehapax That has nothing to do with your Python version. It can't connect to your BTCPay, probably because you're either not running it on a domain or you don't have an SSL certificate for the domain.
> 
> With your issue, the Python library is working correctly; you have an issue on the BTCPay side (probably one of the issues I mention above).

It appears I tried to use the token twice. A common error that is mentioned in the mattermost chat.

**Comment by JeffVandrewJr** [comment]
@thehapax That makes sense. It's also mentioned in the documentation to this library.

**Comment by JeffVandrewJr** [comment]
@imahamat I'm going to close this out since it related to Jupyter.
