### ISSUE TITLE
Testnet pairing

### ISSUE THREAD

**Issue by lizzard-winner** [btcpayserver/btcpay-python#16]
Hello,

When I set up my own btcpayserver I could pair, but when I run it on testnet (I created a store on testnet.demo.btcpayserver.org/) I get `400 Client Error: Bad Request for url: https://testnet.demo.btcpayserver.org/tokens`

The error is on create_client

```
BTCPayClient.create_client(
                    host=settings.BTCPAY_SERVER,
                    code=settings.BTCPAY_SERVER_TOKEN)
```
Any ideas why? Is the server up to date?

**Comment by JeffVandrewJr** [comment]
If you're able to pair to your own server, than that would mean there isn't an issue with Python library itself. I presume the demo server doesn't allow pairing.
