### ISSUE TITLE
Error 400 on get_rates

### ISSUE THREAD

**Issue by tonydavis629** [btcpayserver/btcpay-python#23]
I have my client working with creating invoices. However, when I try to call get_rates(), I get 
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.demo.btcpayserver.org/rates/?cryptoCode=BTC&token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

It's the same client, so I'm thinking this might be a bug?

**Comment by NicolasDorier** [comment]
I will look into it

**Comment by NicolasDorier** [comment]
Fix will be on next version 1.12.4 that we expect to release next week https://github.com/btcpayserver/btcpayserver/pull/5671
